# Generated by Django 4.0.6 on 2022-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['time_create', 'mark'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машина'},
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=255, verbose_name='Марка'),
        ),
    ]
