# Generated by Django 4.0.6 on 2022-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_options_alter_car_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['time_create', 'mark'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публиковано_ли'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=255, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='car',
            name='time_upgrade',
            field=models.DateTimeField(auto_now=True, verbose_name='время изменения'),
        ),
    ]
