# Generated by Django 4.1.1 on 2022-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='photos/%Y/%m/%d/', verbose_name='фотография'),
        ),
    ]
